server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: agropecuario-rest-api
  jackson:
    time-zone: America/Bogota
    date-format: yyyy-MM-dd'T'HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: false

logging:
  level:
    co.unibague.agropecuario: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info