server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: agropecuario-rest-api

  # Configuración de base de datos MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/agropecuario_db?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
    username: agropecuario_user
    password: agropecuario_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuración de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update  # Opciones: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  jackson:
    time-zone: America/Bogota
    date-format: yyyy-MM-dd'T'HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: false

logging:
  level:
    co.unibague.agropecuario: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info